---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
  namespace: release-sphere-services
data:
  redis.conf: |
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    appendonly yes
    protected-mode no
    dir /data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: release-sphere-services
data:
  KAFKA_PROCESS_ROLES: broker,controller
  KAFKA_NODE_ID : "1"
  KAFKA_CONTROLLER_QUORUM_VOTERS : "1@localhost:9093"
  KAFKA_CONTROLLER_LISTENER_NAMES : "CONTROLLER"
  KAFKA_LISTENERS : "PLAINTEXT://:9092,CONTROLLER://:9093"
  KAFKA_ADVERTISED_LISTENERS : "PLAINTEXT://kafka-service:9092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP : "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
  KAFKA_LOG_DIRS : "/tmp/kraft-combined-logs"
