---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: release-sphere-pv
  namespace: release-sphere-services
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany #ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage

  nfs:
    server: 192.168.29.191
    path: /DATA/Backup/nfs
