---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: release-sphere-pvc
  namespace: release-sphere-services
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: release-sphere-pvc
  namespace: release-sphere-services
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-storage
